// File generated by CivicLedger configuration assistant.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6nkmFS9FbWbbFa8-w6_5Yjw5kMr_c6xM',
    appId: '1:676831328377:android:3c6b1a48e714770d90fca8',
    messagingSenderId: '676831328377',
    projectId: 'civicledger-d595d',
    storageBucket: 'civicledger-d595d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6nkmFS9FbWbbFa8-w6_5Yjw5kMr_c6xM',
    appId: '1:676831328377:android:3c6b1a48e714770d90fca8',
    messagingSenderId: '676831328377',
    projectId: 'civicledger-d595d',
    storageBucket: 'civicledger-d595d.firebasestorage.app',
  );
}
