/*
# CivicLedger — Initial Schema for Sistem Pelaporan Masyarakat

Sistem pelaporan & penindakan aspirasi masyarakat berbasis real-time.
Platform memungkinkan warga melaporkan masalah (infrastruktur, kebersihan,
lingkungan, dll), admin memverifikasi & menugaskan petugas, petugas
menyelesaikan laporan dengan bukti foto, dan warga memberi rating.

## 1. New Tables

### `profiles`
- `id` (uuid, PK, references auth.users)
- `email` (text, unique, not null)
- `full_name` (text, not null)
- `phone` (text, nullable)
- `role` (enum: masyarakat, admin, petugas; default masyarakat)
- `wilayah_id` (uuid, FK to wilayah, nullable) — area penugasan untuk petugas
- `is_active` (boolean, default true)
- `created_at` (timestamptz)

### `wilayah` (area/district)
- `id` (uuid, PK)
- `name` (text, not null)
- `code` (text, unique, not null)
- `created_at` (timestamptz)

### `reports` (laporan masyarakat)
- `id` (uuid, PK)
- `ticket_id` (text, unique, not null) — format: CL-YYYYMMDD-XXXX
- `title` (text, not null)
- `description` (text, not null)
- `category` (enum: infrastruktur, lingkungan, kebersihan, pelayanan, keamanan, lainnya)
- `status` (enum: pending, verified, assigned, in_progress, completed, rejected; default pending)
- `priority` (enum: low, medium, high, urgent; default medium)
- `address` (text, not null)
- `latitude` (double precision, nullable)
- `longitude` (double precision, nullable)
- `photo_url` (text, nullable) — foto laporan awal (Supabase Storage)
- `reporter_id` (uuid, FK to profiles, not null)
- `wilayah_id` (uuid, FK to wilayah, nullable)
- `assigned_petugas_id` (uuid, FK to profiles, nullable)
- `assigned_at`, `started_at`, `completed_at` (timestamptz, nullable)
- `rejected_reason` (text, nullable)
- `created_at`, `updated_at` (timestamptz)

### `status_logs` (audit trail perubahan status)
- `id` (uuid, PK)
- `report_id` (uuid, FK to reports, not null)
- `from_status` (enum, nullable)
- `to_status` (enum, not null)
- `changed_by` (uuid, FK to profiles, not null)
- `note` (text, nullable)
- `created_at` (timestamptz)

### `completion_proofs` (bukti foto penyelesaian)
- `id` (uuid, PK)
- `report_id` (uuid, FK to reports, not null)
- `photo_url` (text, not null)
- `note` (text, nullable)
- `uploaded_by` (uuid, FK to profiles, not null)
- `created_at` (timestamptz)

### `upvotes` (dukungan warga pada laporan)
- `id` (uuid, PK)
- `report_id` (uuid, FK to reports, not null)
- `user_id` (uuid, FK to profiles, not null)
- `created_at` (timestamptz)
- UNIQUE (report_id, user_id)

### `comments` (komentar warga pada laporan)
- `id` (uuid, PK)
- `report_id` (uuid, FK to reports, not null)
- `user_id` (uuid, FK to profiles, not null)
- `content` (text, not null)
- `created_at` (timestamptz)

### `ratings` (rating penyelesaian oleh pelapor)
- `id` (uuid, PK)
- `report_id` (uuid, FK to reports, not null)
- `user_id` (uuid, FK to profiles, not null)
- `score` (int 1–5, not null)
- `note` (text, nullable)
- `created_at` (timestamptz)
- UNIQUE (report_id, user_id)

### `petugas_spesialisasi` (kategori yang dikuasai petugas)
- `id` (uuid, PK)
- `petugas_id` (uuid, FK to profiles, not null)
- `category` (enum, not null)
- `created_at` (timestamptz)
- UNIQUE (petugas_id, category)

## 2. Enums
- `user_role`: masyarakat, admin, petugas
- `report_status`: pending, verified, assigned, in_progress, completed, rejected
- `report_priority`: low, medium, high, urgent
- `report_category`: infrastruktur, lingkungan, kebersihan, pelayanan, keamanan, lainnya

## 3. Security (RLS)
- `profiles`: authenticated users can read all profiles (needed for names), update own.
- `wilayah`: anon + authenticated can read (public area list); only admin can insert/update.
- `reports`: authenticated can read all; reporter can insert own; reporter can update own (only while pending); admin & assigned petugas can update.
- `status_logs`: authenticated can read; only the actor (changed_by) can insert (via client), admin can insert.
- `completion_proofs`: authenticated can read; assigned petugas can insert.
- `upvotes`: authenticated can read; users can insert/delete own upvote.
- `comments`: authenticated can read; users can insert/delete own comments.
- `ratings`: authenticated can read; users can insert own rating (one per report).
- `petugas_spesialisasi`: authenticated can read; only admin can insert/delete.

## 4. Notes
- `profiles.id` defaults to `auth.uid()` so insert on signup works.
- `reports.ticket_id` auto-generated by a trigger on insert (format CL-YYYYMMDD-XXXX).
- `reports.updated_at` auto-updated via trigger.
- Status log auto-inserted via trigger on reports.status change.
- Seed data for wilayah included (contoh wilayah Indonesia).
*/

-- ============================================================
-- ENUMS
-- ============================================================
DO $$ BEGIN
  CREATE TYPE user_role AS ENUM ('masyarakat', 'admin', 'petugas');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE report_status AS ENUM ('pending','verified','assigned','in_progress','completed','rejected');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE report_priority AS ENUM ('low','medium','high','urgent');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

DO $$ BEGIN
  CREATE TYPE report_category AS ENUM ('infrastruktur','lingkungan','kebersihan','pelayanan','keamanan','lainnya');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

-- ============================================================
-- TABLES
-- ============================================================

CREATE TABLE IF NOT EXISTS wilayah (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL,
  code text UNIQUE NOT NULL,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS profiles (
  id uuid PRIMARY KEY DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE CASCADE,
  email text UNIQUE NOT NULL,
  full_name text NOT NULL,
  phone text,
  role user_role NOT NULL DEFAULT 'masyarakat',
  wilayah_id uuid REFERENCES wilayah(id) ON DELETE SET NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS reports (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  ticket_id text UNIQUE NOT NULL,
  title text NOT NULL CHECK (char_length(title) >= 5),
  description text NOT NULL CHECK (char_length(description) >= 10),
  category report_category NOT NULL DEFAULT 'lainnya',
  status report_status NOT NULL DEFAULT 'pending',
  priority report_priority NOT NULL DEFAULT 'medium',
  address text NOT NULL,
  latitude double precision,
  longitude double precision,
  photo_url text,
  reporter_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  wilayah_id uuid REFERENCES wilayah(id) ON DELETE SET NULL,
  assigned_petugas_id uuid REFERENCES profiles(id) ON DELETE SET NULL,
  assigned_at timestamptz,
  started_at timestamptz,
  completed_at timestamptz,
  rejected_reason text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS status_logs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  from_status report_status,
  to_status report_status NOT NULL,
  changed_by uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  note text,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS completion_proofs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  photo_url text NOT NULL,
  note text,
  uploaded_by uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS upvotes (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  created_at timestamptz DEFAULT now(),
  UNIQUE (report_id, user_id)
);

CREATE TABLE IF NOT EXISTS comments (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  content text NOT NULL CHECK (char_length(content) >= 1),
  created_at timestamptz DEFAULT now()
);

CREATE TABLE IF NOT EXISTS ratings (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  score integer NOT NULL CHECK (score >= 1 AND score <= 5),
  note text,
  created_at timestamptz DEFAULT now(),
  UNIQUE (report_id, user_id)
);

CREATE TABLE IF NOT EXISTS petugas_spesialisasi (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  petugas_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  category report_category NOT NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE (petugas_id, category)
);

-- ============================================================
-- INDEXES
-- ============================================================
CREATE INDEX IF NOT EXISTS idx_reports_status ON reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_category ON reports(category);
CREATE INDEX IF NOT EXISTS idx_reports_reporter ON reports(reporter_id);
CREATE INDEX IF NOT EXISTS idx_reports_wilayah ON reports(wilayah_id);
CREATE INDEX IF NOT EXISTS idx_reports_assigned_petugas ON reports(assigned_petugas_id);
CREATE INDEX IF NOT EXISTS idx_reports_created_at ON reports(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_status_logs_report ON status_logs(report_id);
CREATE INDEX IF NOT EXISTS idx_upvotes_report ON upvotes(report_id);
CREATE INDEX IF NOT EXISTS idx_comments_report ON comments(report_id);
CREATE INDEX IF NOT EXISTS idx_ratings_report ON ratings(report_id);
CREATE INDEX IF NOT EXISTS idx_petugas_spec_petugas ON petugas_spesialisasi(petugas_id);
CREATE INDEX IF NOT EXISTS idx_profiles_role ON profiles(role);

-- ============================================================
-- TRIGGERS: ticket_id generation, updated_at, status log
-- ============================================================

CREATE SEQUENCE IF NOT EXISTS ticket_seq START 1;

CREATE OR REPLACE FUNCTION generate_ticket_id()
RETURNS text AS $$
DECLARE
  date_part text;
  seq_val integer;
  ticket text;
BEGIN
  date_part := to_char(now(), 'YYYYMMDD');
  SELECT nextval('ticket_seq') INTO seq_val;
  ticket := 'CL-' || date_part || '-' || lpad(seq_val::text, 4, '0');
  RETURN ticket;
END;
$$ LANGUAGE plpgsql VOLATILE;

CREATE OR REPLACE FUNCTION set_ticket_id()
RETURNS trigger AS $$
BEGIN
  IF NEW.ticket_id IS NULL OR NEW.ticket_id = '' THEN
    NEW.ticket_id := generate_ticket_id();
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_set_ticket_id ON reports;
CREATE TRIGGER trg_set_ticket_id
  BEFORE INSERT ON reports
  FOR EACH ROW EXECUTE FUNCTION set_ticket_id();

CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS trigger AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_update_updated_at ON reports;
CREATE TRIGGER trg_update_updated_at
  BEFORE UPDATE ON reports
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

CREATE OR REPLACE FUNCTION log_status_change()
RETURNS trigger AS $$
BEGIN
  IF NEW.status IS DISTINCT FROM OLD.status THEN
    INSERT INTO status_logs (report_id, from_status, to_status, changed_by, note)
    VALUES (NEW.id, OLD.status, NEW.status, auth.uid(), NEW.rejected_reason);
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

DROP TRIGGER IF EXISTS trg_log_status_change ON reports;
CREATE TRIGGER trg_log_status_change
  AFTER UPDATE OF status ON reports
  FOR EACH ROW EXECUTE FUNCTION log_status_change();

-- ============================================================
-- RLS
-- ============================================================

ALTER TABLE wilayah ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE status_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE completion_proofs ENABLE ROW LEVEL SECURITY;
ALTER TABLE upvotes ENABLE ROW LEVEL SECURITY;
ALTER TABLE comments ENABLE ROW LEVEL SECURITY;
ALTER TABLE ratings ENABLE ROW LEVEL SECURITY;
ALTER TABLE petugas_spesialisasi ENABLE ROW LEVEL SECURITY;

-- ---- wilayah ----
DROP POLICY IF EXISTS "read_wilayah" ON wilayah;
CREATE POLICY "read_wilayah" ON wilayah FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "admin_insert_wilayah" ON wilayah;
CREATE POLICY "admin_insert_wilayah" ON wilayah FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "admin_update_wilayah" ON wilayah;
CREATE POLICY "admin_update_wilayah" ON wilayah FOR UPDATE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  ) WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ---- profiles ----
DROP POLICY IF EXISTS "read_profiles" ON profiles;
CREATE POLICY "read_profiles" ON profiles FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_own_profile" ON profiles;
CREATE POLICY "insert_own_profile" ON profiles FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "update_own_profile" ON profiles;
CREATE POLICY "update_own_profile" ON profiles FOR UPDATE
  TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);

-- ---- reports ----
DROP POLICY IF EXISTS "read_reports" ON reports;
CREATE POLICY "read_reports" ON reports FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_own_report" ON reports;
CREATE POLICY "insert_own_report" ON reports FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = reporter_id);

DROP POLICY IF EXISTS "update_reports" ON reports;
CREATE POLICY "update_reports" ON reports FOR UPDATE
  TO authenticated
  USING (
    auth.uid() = reporter_id
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
    OR auth.uid() = assigned_petugas_id
  )
  WITH CHECK (
    auth.uid() = reporter_id
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
    OR auth.uid() = assigned_petugas_id
  );

DROP POLICY IF EXISTS "delete_reports" ON reports;
CREATE POLICY "delete_reports" ON reports FOR DELETE
  TO authenticated USING (
    auth.uid() = reporter_id
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ---- status_logs ----
DROP POLICY IF EXISTS "read_status_logs" ON status_logs;
CREATE POLICY "read_status_logs" ON status_logs FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_status_logs" ON status_logs;
CREATE POLICY "insert_status_logs" ON status_logs FOR INSERT
  TO authenticated WITH CHECK (
    auth.uid() = changed_by
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ---- completion_proofs ----
DROP POLICY IF EXISTS "read_completion_proofs" ON completion_proofs;
CREATE POLICY "read_completion_proofs" ON completion_proofs FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_completion_proofs" ON completion_proofs;
CREATE POLICY "insert_completion_proofs" ON completion_proofs FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (
      SELECT 1 FROM reports r
      WHERE r.id = report_id AND r.assigned_petugas_id = auth.uid()
    )
    OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ---- upvotes ----
DROP POLICY IF EXISTS "read_upvotes" ON upvotes;
CREATE POLICY "read_upvotes" ON upvotes FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_own_upvote" ON upvotes;
CREATE POLICY "insert_own_upvote" ON upvotes FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_upvote" ON upvotes;
CREATE POLICY "delete_own_upvote" ON upvotes FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ---- comments ----
DROP POLICY IF EXISTS "read_comments" ON comments;
CREATE POLICY "read_comments" ON comments FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_own_comment" ON comments;
CREATE POLICY "insert_own_comment" ON comments FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "delete_own_comment" ON comments;
CREATE POLICY "delete_own_comment" ON comments FOR DELETE
  TO authenticated USING (auth.uid() = user_id);

-- ---- ratings ----
DROP POLICY IF EXISTS "read_ratings" ON ratings;
CREATE POLICY "read_ratings" ON ratings FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "insert_own_rating" ON ratings;
CREATE POLICY "insert_own_rating" ON ratings FOR INSERT
  TO authenticated WITH CHECK (auth.uid() = user_id);

-- ---- petugas_spesialisasi ----
DROP POLICY IF EXISTS "read_petugas_spec" ON petugas_spesialisasi;
CREATE POLICY "read_petugas_spec" ON petugas_spesialisasi FOR SELECT
  TO authenticated USING (true);

DROP POLICY IF EXISTS "admin_insert_petugas_spec" ON petugas_spesialisasi;
CREATE POLICY "admin_insert_petugas_spec" ON petugas_spesialisasi FOR INSERT
  TO authenticated WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "admin_delete_petugas_spec" ON petugas_spesialisasi;
CREATE POLICY "admin_delete_petugas_spec" ON petugas_spesialisasi FOR DELETE
  TO authenticated USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

-- ============================================================
-- SEED DATA
-- ============================================================
INSERT INTO wilayah (name, code) VALUES
  ('Jakarta Pusat', 'JKT-PST'),
  ('Jakarta Selatan', 'JKT-SEL'),
  ('Jakarta Barat', 'JKT-BRT'),
  ('Jakarta Timur', 'JKT-TMR'),
  ('Jakarta Utara', 'JKT-UTR'),
  ('Bandung', 'BDG'),
  ('Surabaya', 'SBY'),
  ('Yogyakarta', 'YGY'),
  ('Semarang', 'SMG'),
  ('Bekasi', 'BKS')
ON CONFLICT (code) DO NOTHING;
